base:
  verbose: 3
  cv: 5
  n_jobs: -1

svm:
  C: [0.001, 0.005, 0.01, 0.1]
  kernel: [linear,poly,rbf,sigmoid]

knn:
  n_neighbors: [3,5,7,9,11,13,15]
  algorithm: [auto,ball_tree,kd_tree,brute]
  p: [1,2]

BaggingClassifier:
  n_estimators: 10
  bootstrap: True
  oob_score: True

RandomForest:
  n_estimators: [10,50,100,130]
  criterion: [gini,entropy]
  max_depth: [ 2,3,4,5,6,7 ]
  max_features : [auto,log2]

NB:
  var_smoothing: [1.e-9,0.1, 0.001, 0.5,0.05,0.01,1.e-8,1.e-7,1.e-6,1.e-10,1.e-11]

xgboost:
  n_estimators: [50,100,130]
  max_depth: [3,4,5,6,7,8,9,10,11]
  random_state: 27

stacking:
  cv: 5

GradientBoosting:
  learning_rate: [0.01,0.05,0.1,0.5]
  n_estimators: [50,70,100,130,150]
  min_samples_split: [2,5,7,15,17]
  